name: Tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  # schedule:
  #   - cron: '0 21 * * *'

jobs:
  runTests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: ["18.15.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the era_test_node
        run:
          docker build -t era-test-node-image .

      - name: Start the era_test_node
        run:
          docker run -d --name era_test_node_container -p 8011:8011 era_test_node_image

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn run install:dependencies

      - name: Hello World tests
        run: |
          cd hello-world && yarn run test
