name: Tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  # schedule:
  #   - cron: '0 21 * * *'

jobs:
  runTests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: ["18.15.0"]
        test-pattern: ["cd hello-world && yarn run test"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start the era_test_node
        id: start_node
        run: |
          docker build -t era-test-node-image .
          docker run -d -t era-test-node-image

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn run install:dependencies

      - name: Launch tests
        run: |
          ${{ matrix.test-pattern }}

      - name: Stop the era_test_node and print output logs
        id: stop_node
        if: always()
        run: |
          cat era_test_node_output.log
          kill $PID
